sudo: required
services:
  - docker

before_install:
  - docker build -t qhoan03/docker-and-kubernetes -f Dockerfile.dev .

script:
  - docker run qhoan03/docker-and-kubernetes npm run test -- --coverage
