sudo: required
services:
  - docker

before_install:
  - docker build -t qhoan3008/docker-and-kubernetes -f Dockerfile.dev .

script:
  - docker run qhoan3008/docker-and-kubernetes npm run test -- --coverage
