sudo: required
services:
  - docker

before_install:
  - docker build -t  hoantq03/docker-and-kubernetes -f Dockerfile.dev .

script:
  - docker run  hoantq03/docker-and-kubernetes npm run test -- --coverage
